mrc-2068: Add support for sending to external processes
mrc-ide/rrq pull request #29
Opened 2021-01-22 19:45 UTC by richfitz

This PR adds the ability to run a worker job in a transient process using callr. It is incomplete, but you can try it out in hintr before we finish it. The interface is an argument `separate_process = TRUE` to functions like `$enqueue()`.

* I am not completely sold on `separate_process = TRUE` as a name; we also use "local" for the key (much shorter) and "remote" to describe the separate process. However, what argument we expose should have a default of `FALSE` as these are easier to understand.
* The testing is extremely minimal and does not actually make sure that the job even ran on a different process! We need to include some tests that logging works as expected at least as that was the motivation for this, but we might also write a function that pollutes the global environment
* The core implementation is extremely simple now and shares basically all the worker setup code. This means that the remote will collect any packages and source files that the parent worker uses
* callr is Suggests only; I think that might be ok, what do you think?

2021-02-01 13:41 UTC, r-ash requested changes
This looks good, seen this working with https://github.com/mrc-ide/hintr/pull/252 too. Couple of things looks left over from testing but otherwise looks great.

2021-02-01 13:41 UTC, r-ash commented on .github/workflows/test-coverage.yaml
> +        if: false
This left over from some testing?

2021-02-01 13:41 UTC, r-ash commented on DESCRIPTION
> +    callr,
I think as a suggests is fine

2021-02-01 13:41 UTC, r-ash commented on R/worker_run.R
> +  ## TODO: we might actually pass the worker id through here too and
Want to address this TODO before merging? Or link to a task ID maybe?

2021-02-01 13:52 UTC, richfitz commented on .github/workflows/test-coverage.yaml
> +        if: false
There was a corrupt cache causing issues after an upgrade of an underlying package somehow. I've tried restoring that now

2021-02-01 13:52 UTC, richfitz commented on DESCRIPTION
> +    callr,
ok, this means that you need to make sure we install it in the hintr Dockerfille

2021-02-02 09:55 UTC, r-ash approved these changes

2021-02-02 09:55 UTC, merged