Allow task to be queued with dependencies
mrc-ide/rrq pull request #32
Opened 2021-03-23 17:35 UTC by r-ash

This PR will
* Allow a task to be queued with dependencies using `depends_on` which takes a vector of task_ids for tasks which need to be complete before this task can be run

Thinking that we can build on this to add
* Function to take id and return any prerequisite tasks we are waiting for (and their status)
* Take id and return any tasks which are dependent on this one - possibly less important
* Workflows (if we want to impl at this level) i.e. define some set of work we want to run and have some wrapper of this queue with depends_on which will do the dance of sending the first to `enqueue`, getting the ID and then using that in subsequent calls to `enqueue`

2021-03-23 17:36 UTC, r-ash commented on R/rrq_controller.R
> +      redis$PING()
Is there a better way to work around this? Maybe something I can fix in redux?

2021-03-23 17:38 UTC, r-ash commented on R/dependencies.R
> +                                      task_id, deferred_task_ids) {
I switched around these names several times (in this file and other uses) let me know if still not clear what will be done with which task id. The issue is when we call this from the queuing we have the opposite relationship as we do when calling this from the worker

2021-03-23 17:39 UTC, r-ash commented on R/rrq_controller.R
>  task_submit_n <- function(con, keys, dat, key_complete, queue,
Although this is `task_submit_n` this is only ever called with n = 1 where there could be dependencies. Is that right? Bulk stuff is the only way `n > 1`? I have no test of `n>1` and `depends_on` and I think that probably not something we need to support soon?

2021-03-23 17:40 UTC, r-ash commented on R/dependencies.R
> +  ## NOTE: We're not clearing up dependency keys on the task_id - is that OK?
Is this ok to leave stuff? Or does the cleanup need to clear e.g. list of dependencies for a task? and list of dependents for a task?

2021-03-24 09:00 UTC, richfitz requested changes
This is great, and surprisingly not that complicated in the end.

There's quite a lot of comments about naming - I think you're already struggling with that. One way to help come up with a good naming system is to start writing the vignette content for this (new or in the existing one) and see how the names look that get exposed to the user. The internal names matter much less.

I think that we can forgo the Lua script in the end - see comments there.

2021-03-24 09:00 UTC, richfitz commented on R/common.R
> +TASK_DEFERRED <- "DEFERRED"
Deferred or blocked?

2021-03-24 09:00 UTC, richfitz commented on R/dependencies.R
> +  scripts <- redux::redis_scripts(con, move_to_queue = move_to_queue)
Why does this need to be done in a script? If we _are_ doing it in a script we should move the for loop in there too to reduce the number of roundtrips, and a comment should be added explaining what the reason is (performance and/or avoidance of a race condition)

2021-03-24 09:00 UTC, richfitz commented on R/keys.R
> +  sprintf("%s:task:%s:dependencies.original", queue_id, task_id)
```suggestion
  sprintf("%s:task:%s:dependencies:original", queue_id, task_id)
```

2021-03-24 09:00 UTC, richfitz commented on R/keys.R
> +  sprintf("%s:task:%s:dependents", queue_id, task_id)
Is dependents the inverse of dependencies?

2021-03-24 09:00 UTC, richfitz commented on R/keys.R
> +  sprintf("%s:task:%s:dependencies.original", queue_id, task_id)
not totally sure about "original" here - this is the full set of dependencies? I can't think of anything better than this!

2021-03-24 09:00 UTC, richfitz commented on R/dependencies.R
> +  scripts <- redux::redis_scripts(con, move_to_queue = move_to_queue)
it looks like to me you'd be ok with pipelining all the SREMs

```
res <- con$PIPELINE(lapply(deferred_task_ids, redis$SREM, queue_deferred))
```

Then going through and finding those that have reduced to zero:

```
i <- vlapply(res, identity) == 0
if (any(i)) {
 ...
}
```

with the body of that conditional something like

```
cmds <- lapply(deferred_task_ids[i], function(id)
  list(redis$SREM(key_deferred_queue, id),
       redis$LPUSH(key_queue, id),
       redis$HMSET(key_task_status, id, TASK_PENDING))
con$PIPELINE(unlist(cmds, FALSE, FALSE))
```

2021-03-24 09:00 UTC, richfitz commented on R/rrq_controller.R
> +      if (!is.null(depends_on)) {
Can you move this to a free function to keep these methods short?

2021-03-24 09:00 UTC, richfitz commented on R/rrq_controller.R
> +      vlapply(task_ids, function(id) {
I think that HMGET on the task status will be much faster as it's a single roundtrip

2021-03-24 09:00 UTC, richfitz commented on R/rrq_controller.R
> +      redis$PING()
yeah, this feels like something redux might fix

2021-03-24 09:00 UTC, richfitz commented on R/rrq_controller.R
> +      redis$PING()
however, I wonder if it would be easier here to assemble the list separately from the actual pipeline call, then you can filter NULL out of it first

2021-03-24 09:00 UTC, richfitz commented on R/rrq_controller.R
> +      c(list(
Does redux flatten the list for us? that's cool :)

2021-03-24 09:00 UTC, richfitz commented on R/rrq_controller.R
> +  if (any(response$status %in% incomplete_status)) {
`response$status` will just take the _first_ entry in the command list

```
x <- list(a = 1, a = 2, a = 3)
any(x$a %in% 1) # TRUE
any(x$a %in% 2) # FALSE
```

so you want something more complex:

```
vcapply(response[names(response) == "status"], identity) %in% incomplete_status
```

2021-03-24 09:00 UTC, richfitz commented on R/rrq_controller.R
> +  if (any(response$status %in% incomplete_status)) {
This corner case will only happen when adding more than one task - we don't expose that yet (and you mention that in your comment on the PR) but we will need that eventually

2021-03-24 09:00 UTC, richfitz commented on R/rrq_controller.R
>  task_submit_n <- function(con, keys, dat, key_complete, queue,
We will want n > 1; if you defer for now please add an assertion in the task_submit_n that if depends_on is given then we're only currently allowing one task.

The use case for n > 1 is if we have a workflow that looks like: 

1. run this setup report
2. then run this report over all modelling groups
3. then run this summary report

We'd have n tasks depending on 1 and 1 task depending on n

2021-03-24 09:36 UTC, r-ash commented on R/keys.R
> +  sprintf("%s:task:%s:dependents", queue_id, task_id)
Yes!

2021-03-24 09:48 UTC, r-ash commented on R/common.R
> +TASK_DEFERRED <- "DEFERRED"
I don't mind what we use here. The task are deferred pending another task, or blocked waiting for another task. rq uses deferred but I'm to switch over if you prefer blocked.

2021-03-24 09:49 UTC, richfitz commented on R/common.R
> +TASK_DEFERRED <- "DEFERRED"
If rq uses deferred let's stick with that

2021-03-24 09:54 UTC, r-ash commented on R/dependencies.R
> +  if (identical(task_status, TASK_ERROR)) {
I've changed these to `cancel_dependencies` and `queue_dependencies`, and removed notes about `handle` agree that could be confusing with error handling

2021-03-24 10:01 UTC, r-ash commented on R/dependencies.R
> +  ## NOTE: We're not clearing up dependency keys on the task_id - is that OK?
Thanks yes, added that now

2021-03-24 10:46 UTC, r-ash commented on R/dependencies.R
> +  scripts <- redux::redis_scripts(con, move_to_queue = move_to_queue)
Thanks - tidied that too now

2021-03-24 14:10 UTC, r-ash commented on R/rrq_controller.R
>  task_submit_n <- function(con, keys, dat, key_complete, queue,
Added a test for this case

2021-03-24 14:16 UTC, r-ash commented on R/rrq_controller.R
> +  if (any(response$status %in% incomplete_status)) {
I might not be quite understanding, response here (for 2 dependencies) looks like
```
response <- list(
  "OK",
  "OK",
  status = list("PENDING", "PENDING"),
  2,
  2
)
```
So the check works?
```
Browse[2]> response$status
[[1]]
[1] "PENDING"

[[2]]
[1] "PENDING"

Browse[2]> response$status %in% incomplete_status
[1] FALSE FALSE
```

2021-03-24 14:17 UTC, r-ash commented on R/rrq_controller.R
> +  if (any(response$status %in% incomplete_status)) {
> This corner case will only happen when adding more than one task - we don't expose that yet (and you mention that in your comment on the PR) but we will need that eventually

I think this part of the code isn't affected by trying to queue more than 1 task. `response$status` will be the same if we queue 1 or multiple tasks, it only depends on number of dependencies

2021-03-25 15:38 UTC, richfitz approved these changes

2021-03-25 15:38 UTC, merged