mrc-2268: Add support for delete & cancelling tasks with dependencies and deferred tasks
mrc-ide/rrq pull request #35
Opened 2021-03-29 09:40 UTC by r-ash

* Deferred tasks can be cancelled & deleted
* Tasks cancelled which have dependencies will mark these as impossible (where they cannot be resolved)

2021-03-29 09:44 UTC, r-ash commented on tests/testthat/test-rrq.R
> +  expect_equal(obj$con$SMEMBERS(deferred_set), list(t3))
what we have said is `task_delete` would only clear stuff up for the task id sent, i.e. not do any setting impossible for any of its dependencies. That can leave the list of deferred tasks in a bit of a weird state.

2021-03-29 16:49 UTC, richfitz requested changes
Looks good - one point of clarification and one suggestion.

Could you bump the version number too please?

2021-03-29 16:49 UTC, richfitz commented on R/dependencies.R
> +    n <- length(dependent_ids)
This might be better to do in one set:

```r
dependent_keys <- rrq_key_task_dependents(keys$queue_id, ids)
dependent_ids <- unique(unlist(lapply(dependent_keys, con$SMEMBERS)))
n <- length(dependent_ids)
con$pipeline(
    redis$HMSET(keys$task_status, dependent_ids, rep_len(TASK_IMPOSSIBLE, n)),
    redis$SREM(keys$deferred_set, dependent_ids))
cancel_dependencies(con, keys, dependent_ids)
```

(replacing the for loop)

2021-03-29 16:49 UTC, richfitz commented on tests/testthat/test-rrq.R
> +  expect_equal(obj$con$SMEMBERS(deferred_set), list(t3))
Not sure I follow here.

If the task was `PENDING` we should mark things as `IMPOSSIBLE` and remove them from the list for sure.

If the task was `COMPLETE` (or error etc) we can ignore all dependencies

2021-03-30 10:30 UTC, r-ash commented on tests/testthat/test-rrq.R
> +  expect_equal(obj$con$SMEMBERS(deferred_set), list(t3))
Ok, have updated this so it will clear up dependencies. Added a fair bit of logic so let me know if you think it needs breaking up more as starting to get fairly complicated

2021-03-30 11:38 UTC, richfitz requested changes

2021-03-30 11:38 UTC, richfitz commented on R/rrq_controller.R
> +    cancel <- dependents[status_dependent %in% c(TASK_PENDING, TASK_DEFERRED)]
this can be `== TASK_DEFERRED`

2021-03-30 11:38 UTC, richfitz commented on R/rrq_controller.R
> +  ## B. Their dependencies have not already been set to MISSING, ERROED, etc.
```suggestion
  ## B. Their dependencies have not already been set to MISSING, ERRORED, etc.
Write
```

2021-03-30 11:38 UTC, richfitz commented on R/rrq_controller.R
> +    setNames(lapply(task_ids, function(x) redis$HGET(keys$task_status, x)),
Don't name this one and look up length later as `seq_along(task_ids)`

2021-03-30 11:38 UTC, richfitz commented on R/rrq_controller.R
> +  status <- res[grepl("status_", names(res))]
```
status <- res[seq_along(task_ids)]
```

2021-03-30 12:23 UTC, richfitz approved these changes

2021-03-30 12:23 UTC, merged