Fix taskwait
mrc-ide/rrq pull request #62
Opened 2022-02-28 11:02 UTC by r-ash

This PR will
* Add a helper for running task cleanup
* Call this when tasks set impossible to make sure task result is saved out so that `task_wait` works for IMPOSSIBLE tasks
* Add test to check that `task_wait` works with IMPOSSIBLE

2022-02-28 11:04 UTC, r-ash commented on tests/testthat/test-bulk-support.R
> +  expected <- list(name = quote(ids:::cases),
This was failing as ids:::as_integer_bignum no longer exists in ids package. So I've replaced this with some non-exported function

2022-02-28 11:08 UTC, r-ash commented on R/worker_run.R
> +  run_task_cleanup(private$con, keys, private$store, task$task_id,
This will now do the cleanup in 2 separate calls to redis instead of 1. I think this should be fine as the 2nd call clears up the worker so shouldn't introduce race conditions.

I could alternatively update `run_task_cleanup` to return a set of commands and then run them all in 1 pipeline but thought this would be simpler to understand

2022-02-28 12:14 UTC, richfitz requested changes

2022-02-28 12:14 UTC, richfitz commented on R/task_cleanup.R
> +run_task_cleanup <- function(con, keys, store, task_id, status, value) {
See comments above about making this accept a vector of ids

2022-02-28 12:14 UTC, richfitz commented on R/worker_run.R
> +  run_task_cleanup(private$con, keys, private$store, task$task_id,
It's not obvious to me why this level of refactoring was needed. If possible it would be nice to keep a single pipeline call for a successful job completion as that's part of the limit at which we can get things through the pipeline (in the case of very small jobs) in addition to race conditions. My overall feeling though is that this has not made things easier to understand so perhaps we need multiple versions of this function?

2022-02-28 12:19 UTC, r-ash commented on R/common.R
> +  all = c(TASK_PENDING, TASK_RUNNING, TASK_COMPLETE, TASK_ERROR, TASK_CANCELLED,
thanks, I think I must have removed the wrong one after writing that comment

2022-02-28 12:24 UTC, r-ash commented on R/common.R
> +  waiting = c(TASK_PENDING, TASK_DEFERRED))
We use this to
* check if we can cancel a task, it can be cancelled if it is PENDING, DEFERRED or RUNNING
* after a task is deleted we cancel any dependent tasks which are PENDING or DEFERRED

I think in 2nd case we don't cancel if already RUNNING as it will have resolved any dependencies by that point. Perhaps comment is not helpful, it is really just all waiting tasks.

2022-02-28 12:33 UTC, r-ash commented on R/worker_run.R
> +  run_task_cleanup(private$con, keys, private$store, task$task_id,
We had 3 different functions which were cleaning up tasks
* here in `worker_run_task_cleanup`
* in `task_submit_n` if the submission fails
* in `task_delete` for any dependencies of the task being deleted
where "cleaning up" tasks means setting the status and removing it from queue.

What `worker_run_task_cleanup` was also doing was setting the `rrq_key_task_complete`, `key_complete` the `task_time_complete` the `task_result` and adding it to the `store`. The other cleanup was not doing that. So I think we need the same behaviour everywhere we are setting the final status and doing cleanup of a task so that e.g. `task_wait` will work. The refactoring I hope will mean that we have a common cleanup which does the things we always need to set at the end, like the result, saving to the store etc. to avoid having this issue happen again where we forget to set something.

2022-02-28 14:57 UTC, richfitz commented on R/common.R
> +  waiting = c(TASK_PENDING, TASK_DEFERRED))
I think that `waiting` then might want a better name? `unstarted` is ugly but perhaps more accurate.  Whatever you come up with I can add to the diagram

2022-02-28 15:37 UTC, richfitz requested changes

2022-02-28 15:37 UTC, richfitz commented on R/common.R
> +TASK$terminal <- c(TASK$terminal_fail, TASK_COMPLETE)
Add new test
```r
task_all <- ls(pattern = "^TASK_", envir = asNamespace("rrq"))
expect_setequal(setdiff(task_all, TASK_MISSING), TASK$all)
```

2022-02-28 15:37 UTC, richfitz commented on R/worker_run.R
> +  worker_queue_dependencies(private$con, private$keys, private$store,
It may be that an explicit

```
if (task_status == TASK_SUCCESS) {
  ... happy path cleanup
} else {
  ... deal with depenency cancellation
}
...generic cleanup
```

That way we might be able to share more of the dependency cancellation with the other places that call it

2022-02-28 15:37 UTC, richfitz commented on R/dependencies.R
> +    rep(TASK_IMPOSSIBLE, length(dependent_ids)),
Ideally these two reps come out

2022-02-28 15:37 UTC, richfitz commented on R/dependencies.R
> +    cancel_dependencies(con, keys, store, dependent_ids)
new ticket to do the recursive dependency search on the server in lua (given a vector of ids, return all recursive dependencies in an array, then we can cancel them in one hit)

2022-02-28 15:37 UTC, richfitz commented on R/task_cleanup.R
> +  cmds <- Map(cleanup_one, task_ids, statuses, values)
```suggestion
run_task_cleanup <- function(con, keys, store, task_ids, status, value) {
  cleanup_one <- function(task_id) {
    task_result <- store$set(value, task_id)
    key_complete <- con$HGET(keys$task_complete, task_id)
    list(
      redis$HSET(keys$task_result,        task_id, task_result),
      redis$HSET(keys$task_status,        task_id, status),
      redis$HSET(keys$task_time_complete, task_id, timestamp()),
      redis$RPUSH(rrq_key_task_complete(keys$queue_id, task_id), task_id),
      if (!is.null(key_complete)) {
        redis$RPUSH(key_complete, task_id)
      },
      redis$SREM(keys$deferred_set, task_id)
    )
  }
  cmds <- Map(cleanup_one, task_ids)
```

If dropping the `rep` on calling, then if all tasks are cleaned up with the same status/value the above will work

2022-02-28 15:37 UTC, richfitz commented on R/rrq_controller.R
>    ## If any dependencies will never be satisfied then cleanup and error
Remind us about the race condition here (that we need to queue, then check)

2022-02-28 16:19 UTC, r-ash commented on R/dependencies.R
> +    cancel_dependencies(con, keys, store, dependent_ids)
https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-2964

2022-03-01 19:53 UTC, richfitz approved these changes

2022-03-01 19:53 UTC, richfitz commented on R/rrq_controller.R
> +  lvls <- c(TASK$all, setdiff(unique(status), TASK$all))
ah, this is nice

2022-03-01 19:53 UTC, merged