Mrc 4114 - Queue formatting
mrc-ide/rrq pull request #88
Opened 2023-03-24 11:58 UTC by M-Kusumgar

With this PR I hope to format queues better (they now display vertically with correct indentation)

2023-03-27 14:10 UTC, richfitz requested changes

2023-03-27 14:10 UTC, richfitz commented on R/worker.R
> +  queue_indent <- paste("\n", strrep(" ", max(n)), "    ")
can you please add a test for this that shows that when listening on multiple queues the message does format correctly?

2023-03-27 15:12 UTC, M-Kusumgar commented on R/worker.R
> +  queue_indent <- paste("\n", strrep(" ", max(n)), "    ")
admittedly didnt know the best way to approach this but gave it a try!

2023-03-29 08:09 UTC, richfitz approved these changes
Thanks - I simplified the test in e42c33e, hope you don't mind. Will merge this once it passes

2023-03-29 08:35 UTC, merged